# Pair ETL I

### Conjunto de datos

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-285f5c03e648509897b14f01e0193a5f9a8183c1%2Fventas.csv?alt=media>" %}
Descarga este csv para poder hacer los ejercicios.
{% endfile %}

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-7776d8a6a93a40bc66f3d309faa86a98f015fd94%2Fproductos.csv?alt=media>" %}
Descarga este csv para poder hacer los ejercicios.
{% endfile %}

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-25dbdfd410f5cd031b2bf4adc871062e03206d1f%2Fclientes.csv?alt=media>" %}
Descarga este csv para poder hacer los ejercicios.
{% endfile %}

### **Ejercicios ETL Parte I**

En este caso trabajas en una empresa de venta al por menor de productos italianos y debes realizar la limpieza, transformación e integración de datos de ventas, productos y clientes para su análisis.

Los pasos que deberás seguir en este ejercicio son:

1. **Lectura de la Información:**
   * Leer los archivos CSV (`ventas.csv`, `productos.csv`, `clientes.csv`).
   * Explorar los conjuntos de datos para comprender su estructura, columnas, tipos de datos, etc.

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [11]:
df_ventas = pd.read_csv("ventas.csv")
df_ventas.head()

   ID_Cliente ID_Producto Fecha_Venta  Cantidad  Total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98

In [30]:
df_clientes = pd.read_csv("clientes (2).csv")
df_clientes.head()

,id,first_name,last_name,email,gender,City,Country,Address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle

2. **Transformación de Datos:**
   * Limpiar los datos: manejar valores nulos, eliminar duplicados si los hay, corregir errores tipográficos, etc.
   * Realizar la integración de datos: unir los conjuntos de datos apropiados para obtener una tabla única que contenga información de ventas junto con detalles de productos y clientes.
   * Aplicar transformaciones relevantes según sea necesario: por ejemplo, convertir tipos de datos, renombrar columnas, crear nuevas características derivadas, etc.

**NOTA** Este ejercicio debe realizarse en un archivo `.py`

In [31]:
df_clientes.columns = df_clientes.columns.str.strip().str.lower()

In [32]:
df_clientes.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'city', 'country',
       'address'],
      dtype='object')

In [33]:
columnas_texto = ["first_name","last_name", "city", "country", "gender", "address"]

for col in columnas_texto:
    df_clientes[col] = df_clientes[col].str.strip().str.title()

In [34]:
df_clientes.head()

,id,first_name,last_name,email,gender,city,country,address
0,1,Cheri,Dunsmore,cdunsmore0@instagram.com,Female,Palma De Mallorca,Spain,076 Rockefeller Crossing
1,2,Hunt,Bartomeu,hbartomeu1@nsw.gov.au,Male,Lugo,Spain,0046 Utah Junction
2,3,Michaeline,Paynton,mpaynton2@narod.ru,Female,NaN,Spain,0 Corry Crossing
3,4,Filmer,Eirwin,feirwin3@intel.com,NaN,Leon,Spain,5 American Ash Road
4,5,Tanhya,Lubbock,tlubbock4@huffingtonpost.com,Female,"Hospitalet De Llobregat, L'",Spain,9289 Merry Circle

In [35]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       973 non-null    object
 4   gender      923 non-null    object
 5   city        876 non-null    object
 6   country     846 non-null    object
 7   address     959 non-null    object
dtypes: int64(1), object(7)
memory usage: 62.6+ KB

In [37]:
df_ventas.columns = df_ventas.columns.str.strip().str.lower()
df_ventas.head()

   id_cliente id_producto fecha_venta  cantidad  total
0         723          A1  2023-11-22         2  17.98
1         498          C3  2023-11-21         1   5.49
2         121          D4  2023-11-20         3  32.97
3         885         L12  2023-11-19         1   6.49
4         347         Q17  2023-11-18         2   7.98

In [38]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_cliente   100 non-null    int64
 1   id_producto  100 non-null    object
 2   fecha_venta  100 non-null    object
 3   cantidad     100 non-null    int64
 4   total        100 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ KB

In [39]:
df_ventas["fecha_venta"] = pd.to_datetime(df_ventas["fecha_venta"])

In [40]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_cliente   100 non-null    int64
 1   id_producto  100 non-null    object
 2   fecha_venta  100 non-null    datetime64[ns]
 3   cantidad     100 non-null    int64
 4   total        100 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 4.0+ KB

In [43]:
df_merge = pd.merge(df_clientes, df_ventas, how = "outer", left_on = "id", right_on = "id_cliente")

df_merge.sample(10)

,id,first_name,last_name,email,gender,city,country,address,id_cliente,id_producto,fecha_venta,cantidad,total
356,332,Matthus,Fetherston,mfetherston97@yandex.ru,Polygender,Fuenlabrada,Spain,28558 Morrow Parkway,NaN,NaN,NaT,NaN,NaN
304,284,Dona,Jakeman,djakeman7v@myspace.com,Female,Santa Cruz De Tenerife,Spain,1181 Trailsway Center,NaN,NaN,NaT,NaN,NaN
606,567,Chickie,Corkhill,ccorkhillfq@china.com.cn,Male,Valladolid,Spain,9 4Th Street,567.0,BO83,2023-10-27,2.0,12.50
490,465,Gerrie,Macgauhy,gmacgauhycw@storify.com,Genderqueer,Valencia,Spain,4 Tennyson Parkway,465.0,AY51,2023-10-20,1.0,7.25
263,243,Laurie,Harlowe,lharlowe6q@csmonitor.com,NaN,Ceuta,Spain,NaN,NaN,NaN,NaT,NaN,NaN
673,634,Donnie,Boller,dbollerhl@webeden.co.uk,Male,Logroño,Spain,233 Luster Pass,NaN,NaN,NaT,NaN,NaN
885,840,Torre,Ortiga,tortiganb@facebook.com,Male,NaN,Spain,477 Scofield Junction,NaN,NaN,NaT,NaN,NaN
836,792,Cammy,Rising,crisinglz@biglobe.ne.jp,Female,Logroño,Spain,549 Dwight Alley,NaN,NaN,NaT,NaN,NaN
679,640,Nadiya,Girling,ngirlinghr@quantcast.com,Female,NaN,Spain,119 Laurel Street,NaN,NaN,NaT,NaN,NaN
456,432,Minor,Hryskiewicz,mhryskiewiczbz@businessweek.com,Male,Dos Hermanas,Spain,3 Declaration Way,432.0,AH34,2023-11-06,3.0,19.47

In [44]:
df_merge["gender"].unique()

array(['Female', 'Male', nan, 'Polygender', 'Genderfluid', 'Non-Binary',
       'Agender', 'Bigender', 'Genderqueer'], dtype=object)

In [46]:
df_merge['gender'].isna().mean() * 100

np.float64(8.504672897196262)

In [47]:
df_merge['gender'].fillna("Unknown", inplace=True)

In [49]:
df_merge['gender'].isna().mean() * 100

np.float64(0.0)

In [50]:
df_merge["city"].unique()

array(['Palma De Mallorca', 'Lugo', nan, 'Leon',
       "Hospitalet De Llobregat, L'", 'Lleida', 'Santander', 'Malaga',
       'Valladolid', 'Murcia', 'Pamplona/Iruña', 'Barcelona', 'Palencia',
       'Pontevedra', 'Girona', 'Fuenlabrada', 'Jaen', 'Almeria',
       'Elx/Elche', 'Getafe', 'Sevilla', 'Coruña, A', 'Zaragoza',
       'Palmas De Gran Canaria, Las', 'Cadiz', 'Tarragona',
       'Santiago De Compostela', 'Donostia-San Sebastian', 'Cartagena',
       'Madrid', 'Ceuta', 'Vigo', 'Valencia', 'Sabadell', 'Granada',
       'Albacete', 'Teruel', 'Aviles',
       'Castellon De La Plana/Castello De La Pla', 'Vitoria-Gasteiz',
       'Zamora', 'Santa Cruz De Tenerife', 'Logroño', 'Torrevieja',
       'Leganes', 'Gijon', 'Toledo', 'Badajoz', 'Dos Hermanas', 'Ourense',
       'Ferrol', 'Salamanca', 'Sant Cugat Del Valles', 'Huesca',
       'Alicante/Alacant', 'Telde'], dtype=object)

In [51]:
df_merge['city'].isna().mean() * 100

np.float64(12.897196261682243)

In [52]:
df_merge['city'].fillna("Unknown", inplace=True)

C:\Users\Clara\AppData\Local\Temp\ipykernel_18848\1688343942.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merge['city'].fillna("Unknown", inplace=True)

In [54]:
df_merge['address'].fillna("Unknown", inplace=True)

C:\Users\Clara\AppData\Local\Temp\ipykernel_18848\312509987.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merge['address'].fillna("Unknown", inplace=True)

In [57]:
df_merge.drop(columns="id_cliente", inplace=True)

In [ ]:
columnas_imputar = ["id_producto", "cantidad", "total"]