# Pair Pandas

### Datos

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-7f59432ebab9fd9c2ee4f639b4c5c063bc4dcc9e%2Fmedallas.csv?alt=media>" %}
Descarga este csv para poder hacer los ejercicios de *pair programming*.
{% endfile %}

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-901ed564aa6d8c22a367a27710e669da7971fba8%2Fworld-data-2023_part1.csv?alt=media>" %}
Descarga este csv para poder hacer los ejercicios.
{% endfile %}

### Ejercicios

1. ¿Qué diferencia hay entre una *Serie* y un *DataFrame*?

Serie- Unidimensional
DataFrame- Bidimensional

2. Es el turno de los *DataFrames*
   * Crea un *array* de dos dimensiones con 4 filas y 3 columnas.
   * Convierte el *array* en un *DataFrame* donde las columnas se llamen "España", "Francia" e "Italia".
   * Descarga el archivo "medallas" y carga el *DataFrame*.
   * Usando el `loc` extrae todas las columnas de la fila de Tailandia.
   * Usando el `loc` extrae todas las columnas de China e Irán.
   * Usando el `loc` extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
   * Usando el `iloc` extrae la información de la India. Devolved todas las columnas.
   * Usando el `iloc` extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
   * Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
   * Contesta a las siguientes preguntas:
     * ¿Qué país consiguió más de 200 medallas de oro?
     * ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
     * ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
   * Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [1]:
import pandas as pd
import numpy as np

In [2]:
array = np.random.randint(0,13, size=(4,3))

In [4]:
df = pd.DataFrame(array, columns=['España', 'Francia', 'Italia'])

df

   España  Francia  Italia
0       2        3       4
1       4        4       5
2       2       10       1
3      12        7       8

In [24]:
df_medallas = pd.read_csv('medallas.csv', index_col = 'País')

df_medallas

                 Unnamed: 0   Oro  Plata  Bronce
País
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [25]:
df_medallas.iloc[6, :]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

In [26]:
df_medallas.loc['Tailandia', :]

Unnamed: 0      7
Oro           132
Plata         175
Bronce        278
Name: Tailandia, dtype: int64

In [27]:
df_medallas.loc[['China', 'Irán'], :]

       Unnamed: 0   Oro  Plata  Bronce
País
China           1  1473    994     720
Irán            4   179    181     197

In [28]:
df_medallas.loc[['China', 'Irán'], 'Oro':'Bronce']

        Oro  Plata  Bronce
País
China  1473    994     720
Irán    179    181     197

In [29]:
df_medallas

                 Unnamed: 0   Oro  Plata  Bronce
País
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [30]:
df_medallas.iloc[5,:]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

In [31]:
df_medallas.iloc[1::2]

                 Unnamed: 0   Oro  Plata  Bronce
País
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [34]:
df_medallas.iloc[1::2, 1:4]

                  Oro  Plata  Bronce
País
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

In [35]:
df_medallas

                 Unnamed: 0   Oro  Plata  Bronce
País
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [46]:
filtro = df_medallas['Oro'] > 200

In [47]:
df_medallas[filtro]

               Unnamed: 0   Oro  Plata  Bronce
País
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [49]:
filtro = (df_medallas['Oro'] > 200) & (df_medallas ['Plata'] > 1000)
df_medallas[filtro]

       Unnamed: 0   Oro  Plata  Bronce
País
Japón           2  1032   1037     985

In [51]:
filtro = (df_medallas['Oro'] > 200) | (df_medallas ['Bronce'] > 700)
df_medallas[filtro]

               Unnamed: 0   Oro  Plata  Bronce
País
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [52]:
df_medallas['Total'] = (df_medallas['Oro']) + (df_medallas['Plata']) + (df_medallas['Bronce'])

In [57]:
df_medallas['Total'] = df_medallas[['Oro', 'Plata', 'Bronce']].sum(axis = 1)

In [58]:
df_medallas

                 Unnamed: 0   Oro  Plata  Bronce  Total
País
China                     1  1473    994     720   3187
Japón                     2  1032   1037     985   3054
Corea del Sur             3   745    663     827   2235
Irán                      4   179    181     197    557
Kazajistán                5   155    158     224    537
India                     6   154    202     315    671
Tailandia                 7   132    175     278    585
Indonesia                 8   112    131     240    483
China Taipéi              9    99    144     276    519
Corea del Norte          10    91    120     235    446

In [53]:
df_medallas

                 Unnamed: 0   Oro  Plata  Bronce  Total
País
China                     1  1473    994     720   3187
Japón                     2  1032   1037     985   3054
Corea del Sur             3   745    663     827   2235
Irán                      4   179    181     197    557
Kazajistán                5   155    158     224    537
India                     6   154    202     315    671
Tailandia                 7   132    175     278    585
Indonesia                 8   112    131     240    483
China Taipéi              9    99    144     276    519
Corea del Norte          10    91    120     235    446

3. Momento de trabajar con Series. Contesta a las siguientes preguntas:
   * Crea dos listas:
     * Una que se llame "valores" que tenga 7 números aleatorios.
     * Otra que se llame "indices" que tenga 7 *strings* que se llamen como los días de la semana.
   * A partir de estas dos listas crea una *Serie* donde la variable "valores" sean los valores de la *Serie* y la variable *indices* sean los índices de la *Serie*.
   * A partir de las dos listas anteriores crea un diccionario usando un bucle *for*. Para hacer esto tenemos el método `zip` que nos permite iterar por dos listas a la vez. Más información sobre este método [aquí](https://www.programiz.com/python-programming/methods/built-in/zip).
   * Crea una *Serie* con el diccionario creado en el punto anterior.
   * ¿Qué forma tiene esta última Serie?
   * ¿Qué tipo de datos tiene?
   * ¿Qué tamaño tiene?
   * ¿Cuáles son los índices de la Serie?
   * ¿Y los *values*?
   * Extrae el valor para el índice "lunes"
   * Extrae el valor para el índice "lunes", "martes" y "miércoles".
   * Extrae el valor para el índice "lunes" y "domingo".

### Más ejercicios de loc e iloc

Para realizar estos ejercicios deberéis usar el conjunto de datos de `world-data-2023-part1.csv`.

1. Selecciona todas las columnas de las filas 2 a 4 (inclusive) utilizando `loc`.
2. Utilizando `loc`, filtra el conjunto de datos para mostrar solo las filas donde la densidad (columna "Birth Rate") es mayor a 30.
3. Utilizando `loc` selecciona las columnas "Country" y "Capital/Major City" de las filas donde el porcentaje de tierra agrícola (columna "Fertility Rate") es superior al 3.
4. Selecciona todas las filas de las columnas 0 a 4 (excluyendo la columna 4) utilizando `iloc`.
5. Encuentra el valor en la fila 2 y columna 7 utilizando `iloc`.
6. Selecciona todas las filas para las columnas 0, 2, y 5 utilizando `iloc`.
7. Encuentra el valor de "Gasoline Price" para el país cuya abreviatura es "AL" utilizando `loc`.
8. Selecciona todas las columnas para el país cuya capital es "Tirana" utilizando `loc`.
9. Filtra el conjunto de datos para mostrar solo las filas donde el índice de CPI (columna "CPI") sea igual a 128.85.
10. Encuentra la densidad (columna "Density\n(P/Km2)") para el país cuya abreviatura es "AD" utilizando `loc`.
11. Selecciona las columnas "Country" y "Co2-Emissions".
12. Filtra el conjunto de datos para mostrar solo las filas donde el índice de CPI cambió un 2% (columna "CPI Change (%)").
13. Encuentra la tasa de natalidad (columna "Birth Rate") para el país con la abreviatura "AF" utilizando `loc`.
14. Selecciona todas las columnas de las filas 3 a 5 (excluyendo la fila 5) utilizando `iloc`.
15. Selecciona las columnas 1, 3 y 6 para todas las filas utilizando `iloc`.