# Pair Unión y Limpieza de Datos

## **Ejercicios Unión de Datos**

Para realizar estos ejercicios deberéis usar el conjunto de datos de `world-data-2023-part1.csv` y el de `world-data-2023-part2.csv`.

Hoy tenemos un dataset nuevo, en este encontraremos las siguientes columnas:

* **GDP:** Producto Interno Bruto, el valor total de bienes y servicios producidos en el país.
* **Gross primary education enrollment (%):** Tasa bruta de matriculación en educación primaria.
* **Gross tertiary education enrollment (%):** Tasa bruta de matriculación en educación terciaria.
* **Infant mortality:** Número de muertes por cada 1,000 nacidos vivos antes de cumplir un año de edad.
* **Largest city:** Nombre de la ciudad más grande del país.
* **Life expectancy:** Número promedio de años que se espera que viva un recién nacido.
* **Maternal mortality ratio:** Número de muertes maternas por cada 100,000 nacidos vivos.
* **Minimum wage:** Nivel de salario mínimo en moneda local.
* **Official language:** Idioma(s) oficial(es) hablado(s) en el país.
* **Out of pocket health expenditure:** Porcentaje del gasto total en salud pagado directamente por individuos.
* **Physicians per thousand:** Número de médicos por cada mil personas.
* **Population:** Población total del país.
* **Population: Labor force participation (%):** Porcentaje de la población que forma parte de la fuerza laboral.
* **Tax revenue (%):** Ingresos fiscales como porcentaje del PIB.
* **Total tax rate:** Carga fiscal total como porcentaje de las ganancias comerciales.
* **Unemployment rate:** Porcentaje de la fuerza laboral que está desempleada.
* **Urban\_population:** Porcentaje de la población que vive en áreas urbanas.
* **coordinates:** Coordenadas de latitud y longitud de la ubicación del país.
* **country:** Nombre del país.

Tienes a tu disposición dos conjuntos de datos, "world-data-2023-part1.csv" y "world-data-2023-part2.csv", que contienen información de una serie de indicadores y datos de distintos países. Tu tarea es explorar estos conjuntos de datos y determinar qué tienen en común en términos de columnas y datos.

Luego, debes crear un nuevo DataFrame que combine la información de ambos conjuntos de datos en un solo conjunto de datos. Para hacerlo, debes seleccionar el método de unión de Pandas que consideres más apropiado para esta situación y justificar por qué crees que ese método es el mejor en tu informe.

Asegúrate de realizar los siguientes pasos:

1. Explora y carga ambos conjuntos de datos en pandas DataFrames.

In [1]:
import pandas as pd
import numpy as np

In [7]:
pd_1 = pd.read_csv('world-data-2023_part1.csv', index_col = 0)

pd_1.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

In [8]:
pd_2 = pd.read_csv('world-data-2023_part2.csv', index_col = 0)

pd_2.head()

,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

2. Identifica las columnas comunes entre los dos conjuntos de datos.

In [9]:
pd_1.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='object')

In [11]:
pd_2.columns

Index(['GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population', 'country',
       'coordinates'],
      dtype='object')

3. Utiliza el método de unión de Pandas que consideres más adecuado para combinar los datos de ambos años en un solo DataFrame.

In [14]:
df_merge = pd_1.merge(pd_2, left_on='Country', right_on = 'country', how= 'outer')

df_merge.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,country,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",Afghanistan,"('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",Albania,"('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",Algeria,"('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",Andorra,"('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",Angola,"('-11.202692 ', '17.873887')"

In [15]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Country                                    195 non-null    object
 1   Density
(P/Km2)                            195 non-null    object
 2   Abbreviation                               188 non-null    object
 3   Agricultural Land( %)                      188 non-null    object
 4   Land Area(Km2)                             194 non-null    object
 5   Armed Forces size                          171 non-null    object
 6   Birth Rate                                 189 non-null    float64
 7   Calling Code                               194 non-null    float64
 8   Capital/Major City                         192 non-null    object
 9   Co2-Emissions                              188 non-null    object
 10  CPI                                        178 non-null    object
 11  CPI Change (%)                             179 non-null    object
 12  Currency-Code                              180 non-null    object
 13  Fertility Rate                             188 non-null    float64
 14  Forested Area (%)                          188 non-null    object
 15  Gasoline Price                             175 non-null    object
 16  GDP                                        193 non-null    object
 17  Gross primary education enrollment (%)     188 non-null    object
 18  Gross tertiary education enrollment (%)    183 non-null    object
 19  Infant mortality                           189 non-null    float64
 20  Largest city                               189 non-null    object
 21  Life expectancy                            187 non-null    float64
 22  Maternal mortality ratio                   181 non-null    float64
 23  Minimum wage                               150 non-null    object
 24  Official language                          190 non-null    object
 25  Out of pocket health expenditure           188 non-null    object
 26  Physicians per thousand                    188 non-null    float64
 27  Population                                 194 non-null    object
 28  Population: Labor force participation (%)  176 non-null    object
 29  Tax revenue (%)                            169 non-null    object
 30  Total tax rate                             183 non-null    object
 31  Unemployment rate                          176 non-null    object
 32  Urban_population                           190 non-null    object
 33  country                                    195 non-null    object
 34  coordinates                                195 non-null    object
dtypes: float64(7), object(28)
memory usage: 53.4+ KB

4. Explica por qué elegiste ese método de unión y cómo se llevaron a cabo los pasos anteriores.

Hemos elegido el método de unión merge con un outer join porque no queriamos que nos borrara ningún resgitro


## **Ejercicios de Limpieza**

1. Después de la unión de datos, tenemos dos columnas de "country". Elimina una de ellas.

In [16]:
df_merge.drop('country', axis = 1, inplace = True)
df_merge

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,coordinates
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,Pashto,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')"
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,Albanian,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')"
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,Arabic,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')"
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,Catalan,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')"
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,Portuguese,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,Spanish,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368","('6.42375 ', '-66.58973')"
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,Vietnamese,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140","('14.058324 ', '108.277199')"
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,Arabic,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523","('15.552727 ', '48.516388')"
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,English,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713","('-13.133897 ', '27.849332')"
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,Shona,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305","('-19.015438 ', '29.154857')"

In [17]:
df_merge.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price', 'GDP', 'Gross primary education enrollment (%)',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Largest city', 'Life expectancy', 'Maternal mortality ratio',
       'Minimum wage', 'Official language', 'Out of pocket health expenditure',
       'Physicians per thousand', 'Population',
       'Population: Labor force participation (%)', 'Tax revenue (%)',
       'Total tax rate', 'Unemployment rate', 'Urban_population',
       'coordinates'],
      dtype='object')

2. Los nombres de las columnas no son homogeneos. Cambia los nombres de las columnas de tal forma que:
   * No tengan espacios.
   * Estén en minúscula.
   * No tengan paréntesis, es decir, quitar "(%)", "(Km2)".
   * Algunas columnas tiene "\n". Eliminalos de los nombres de las columnas.
   * Algunas columnas tienen ":". Eliminalos de los nombres de las columnas.

In [24]:
nombres_nuevos= {}

for col in df_merge.columns:
    nombres_nuevos[col] = col.replace('(%)', "").replace('(Km2)', "").replace('\n(P/Km2)',"").replace('( %)', "").replace(':', "").strip().lower()

nombres_nuevos

{'Country': 'country',
 'Density\n(P/Km2)': 'density',
 'Abbreviation': 'abbreviation',
 'Agricultural Land( %)': 'agricultural land',
 'Land Area(Km2)': 'land area',
 'Armed Forces size': 'armed forces size',
 'Birth Rate': 'birth rate',
 'Calling Code': 'calling code',
 'Capital/Major City': 'capital/major city',
 'Co2-Emissions': 'co2-emissions',
 'CPI': 'cpi',
 'CPI Change (%)': 'cpi change',
 'Currency-Code': 'currency-code',
 'Fertility Rate': 'fertility rate',
 'Forested Area (%)': 'forested area',
 'Gasoline Price': 'gasoline price',
 'GDP': 'gdp',
 'Gross primary education enrollment (%)': 'gross primary education enrollment',
 'Gross tertiary education enrollment (%)': 'gross tertiary education enrollment',
 'Infant mortality': 'infant mortality',
 'Largest city': 'largest city',
 'Life expectancy': 'life expectancy',
 'Maternal mortality ratio': 'maternal mortality ratio',
 'Minimum wage': 'minimum wage',
 'Official language': 'official language',
 'Out of pocket health expenditure': 'out of pocket health expenditure',
 'Physicians per thousand': 'physicians per thousand',
 'Population': 'population',
 'Population: Labor force participation (%)': 'population labor force participation',
 'Tax revenue (%)': 'tax revenue',
 'Total tax rate': 'total tax rate',
 'Unemployment rate': 'unemployment rate',
 'Urban_population': 'urban_population',
 'coordinates': 'coordinates'}

In [27]:
df_merge.rename(columns = nombres_nuevos, inplace = True )

In [28]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 34 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   country                               195 non-null    object
 1   density                               195 non-null    object
 2   abbreviation                          188 non-null    object
 3   agricultural land                     188 non-null    object
 4   land area                             194 non-null    object
 5   armed forces size                     171 non-null    object
 6   birth rate                            189 non-null    float64
 7   calling code                          194 non-null    float64
 8   capital/major city                    192 non-null    object
 9   co2-emissions                         188 non-null    object
 10  cpi                                   178 non-null    object
 11  cpi change                            179 non-null    object
 12  currency-code                         180 non-null    object
 13  fertility rate                        188 non-null    float64
 14  forested area                         188 non-null    object
 15  gasoline price                        175 non-null    object
 16  gdp                                   193 non-null    object
 17  gross primary education enrollment    188 non-null    object
 18  gross tertiary education enrollment   183 non-null    object
 19  infant mortality                      189 non-null    float64
 20  largest city                          189 non-null    object
 21  life expectancy                       187 non-null    float64
 22  maternal mortality ratio              181 non-null    float64
 23  minimum wage                          150 non-null    object
 24  official language                     190 non-null    object
 25  out of pocket health expenditure      188 non-null    object
 26  physicians per thousand               188 non-null    float64
 27  population                            194 non-null    object
 28  population labor force participation  176 non-null    object
 29  tax revenue                           169 non-null    object
 30  total tax rate                        183 non-null    object
 31  unemployment rate                     176 non-null    object
 32  urban_population                      190 non-null    object
 33  coordinates                           195 non-null    object
dtypes: float64(7), object(27)
memory usage: 51.9+ KB

3. La columnas `coordinates` tiene la latitud y la longitud en una sola columna. Crea dos columnas nuevas, una con la longitud y otra con la latitud. Una vez hecho, elimina la columna de `coordinates`.

In [38]:
df_merge["coordinates"].str.split(",", expand = True)

                  0               1
0      ('33.93911 '    '67.709953')
1     ('41.153332 '    '20.168331')
2     ('28.033886 '     '1.659626')
3     ('42.506285 '     '1.521801')
4    ('-11.202692 '    '17.873887')
..              ...             ...
190     ('6.42375 '    '-66.58973')
191   ('14.058324 '   '108.277199')
192   ('15.552727 '    '48.516388')
193  ('-13.133897 '    '27.849332')
194  ('-19.015438 '    '29.154857')

[195 rows x 2 columns]

In [39]:
df_merge[["latitud", "longitud"]] = df_merge["coordinates"].str.split(",", expand = True).get([0,1])

In [40]:
df_merge

,country,density,abbreviation,agricultural land,land area,armed forces size,birth rate,calling code,capital/major city,co2-emissions,...,physicians per thousand,population,population labor force participation,tax revenue,total tax rate,unemployment rate,urban_population,coordinates,latitud,longitud
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273","('33.93911 ', '67.709953')",('33.93911 ','67.709953')
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593","('41.153332 ', '20.168331')",('41.153332 ','20.168331')
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100","('28.033886 ', '1.659626')",('28.033886 ','1.659626')
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873","('42.506285 ', '1.521801')",('42.506285 ','1.521801')
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025","('-11.202692 ', '17.873887')",('-11.202692 ','17.873887')
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368","('6.42375 ', '-66.58973')",('6.42375 ','-66.58973')
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140","('14.058324 ', '108.277199')",('14.058324 ','108.277199')
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523","('15.552727 ', '48.516388')",('15.552727 ','48.516388')
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713","('-13.133897 ', '27.849332')",('-13.133897 ','27.849332')
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305","('-19.015438 ', '29.154857')",('-19.015438 ','29.154857')

In [51]:
df_merge['latitud'] = df_merge['latitud'].str.replace('(', "").str.replace("'", "").str.strip()
df_merge['longitud'] = df_merge['longitud'].str.replace(')', "").str.replace("'", "").str.strip()

In [54]:
df_merge.drop(columns='coordinates', inplace=True)

In [55]:
df_merge

,country,density,abbreviation,agricultural land,land area,armed forces size,birth rate,calling code,capital/major city,co2-emissions,...,out of pocket health expenditure,physicians per thousand,population,population labor force participation,tax revenue,total tax rate,unemployment rate,urban_population,latitud,longitud
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.93911,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175",...,45.80%,1.92,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.42375,-66.58973
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",...,43.50%,0.82,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.015438,29.154857

4. Las columnas `unemployment_rate`, `total_tax_rate`, `tax_revenue`, `population_labor_force_participation`, `out_of_pocket_health_expenditure`, `gross_tertiary_education_enrollment`, `gross_primary_education_enrollment`, `forested_area`, `cpi_change`, `agricultural_land` tienen "%". Elimina los "%" de los valores de las columnas.

In [57]:
for col in df_merge.columns:
    df_merge['col'] = df_merge['col'].str.replace('%', "").str.strip()

KeyError: 'col'

5. Haz lo mismo para las columnas de `gasoline_price`, `gdp`, `minimum_wage`, pero eliminando "$".
6. Guarda el DataFrame para usarlo posteriormente.

## **Ejercicios de Filtrado**

1. Encuentra todos los países cuya mortalidad infantil esté entre 40 y 50 personas por kilómetro cuadrado.
2. Encuentra los países cuyas tasas de natalidad son mayores o iguales a 20 y su esperanza de vida es mayor de 75 años.
3. Encuentra las ciudades cuyos paises contienen la palabra "la" en su nombre.
4. Encuentra los países cuyos medicos por cada 1000 habitantes (physicians\_per\_thousand) sea mayores de 5.
5. Encuentra los países cuyatasa de fertilidad sea mayor a 6.
6. Encuentra los países cuya moneda es el euro (EUR) y tienen una tasa de natalidad superior al promedio.
7. Encuentra los países cuyas tasas de mortalidad infantil son superiores a 70.