# Pair EDA

### Conjunto de datos:

{% file src="<https://931940412-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FiDkWIWBqfl4XxuhVbroM%2Fuploads%2Fgit-blob-901ed564aa6d8c22a367a27710e669da7971fba8%2Fworld-data-2023_part1.csv?alt=media>" %}
Descarga este csv para poder hacer los ejercicios.
{% endfile %}

Para realizar estos ejercicios deberéis usar el conjunto de datos de `world-data-2023-part1.csv`.

En este fichero encontraremos la siguiente información:

* **Country:** Nombre del país.
* **Density\n(P/Km2):** Densidad de población medida en personas por kilómetro cuadrado.
* **Abbreviation:** Abreviatura o código que representa al país.
* **Agricultural Land( %):** Porcentaje del área total de tierra utilizada con fines agrícolas.
* **Land Area(Km2):** Área total de tierra del país en kilómetros cuadrados.
* **Armed Forces size:** Tamaño de las fuerzas armadas en el país.
* **Birth Rate:** Número de nacimientos por cada 1,000 habitantes por año.
* **Calling Code:** Código internacional de llamada para el país.
* **Capital/Major City:** Nombre de la capital o ciudad principal.
* **Co2-Emissions:** Emisiones de dióxido de carbono en toneladas.
* **CPI:** Índice de Precios al Consumidor (IPC), una medida de la inflación y el poder adquisitivo.
* **CPI Change (%):** Cambio porcentual en el Índice de Precios al Consumidor en comparación con el año anterior.
* **Currency-Code:** Código de moneda utilizado en el país.
* **Fertility Rate:** Número promedio de hijos nacidos de una mujer durante su vida.
* **Forested Area (%):** Porcentaje del área total cubierta por bosques.
* **Gasoline Price:** Precio de la gasolina por litro en moneda local.

In [4]:
import pandas as pd
import numpy as np

In [5]:
df_data = pd.read_csv('world-data-2023_part.csv',index_col = 0)

In [6]:
df_data

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34


### Ejercicios de exploración del conjunto de datos

1. Muestra las primeras 5 filas del conjunto de datos.

In [7]:
df_data.head(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.02,0.80%,$0.28
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.27,34.00%,$1.51
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.52,46.30%,$0.97

2. Muestra las últimas 5 filas del conjunto de datos.

In [8]:
df_data.tail(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.88,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.27,52.70%,$0.00
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.75,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.05,48.10%,$0.80
192,Yemen,56,YE,44.60%,"527,968","40,000",30.45,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.79,1.00%,$0.92
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.19,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.63,65.20%,$1.40
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.68,263.0,Harare,"10,983",105.51,0.90%,NaN,3.62,35.50%,$1.34

3. Muestra una muestra aleatoria de 5 filas del conjunto de datos.

In [9]:
df_data.sample(5)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
50,Ecuador,71,EC,22.20%,"283,561","41,000",19.72,593.0,Quito,"41,155",124.14,0.30%,USD,2.43,50.20%,$0.61
69,Guinea,53,GN,59.00%,"245,857","13,000",36.36,224.0,Conakry,"2,996",262.95,9.50%,GNF,4.70,25.80%,$0.90
99,Lithuania,43,LT,47.20%,"65,300","34,000",10.00,370.0,Vilnius,"12,963",118.38,2.30%,EUR,1.63,34.80%,$1.16
104,Maldives,"1,802",MV,26.30%,298,"5,000",14.20,960.0,Mal�,"1,445",99.7,0.20%,NaN,1.87,3.30%,$1.63
63,Georgia,57,GE,34.50%,"69,700","26,000",13.47,995.0,Tbilisi,"10,128",133.61,4.90%,GEL,2.06,40.60%,$0.76

4. Muestra el nombre de todas las columnas en el conjunto de datos.

In [10]:
df_data.columns

Index(['Country', 'Density\n(P/Km2)', 'Abbreviation', 'Agricultural Land( %)',
       'Land Area(Km2)', 'Armed Forces size', 'Birth Rate', 'Calling Code',
       'Capital/Major City', 'Co2-Emissions', 'CPI', 'CPI Change (%)',
       'Currency-Code', 'Fertility Rate', 'Forested Area (%)',
       'Gasoline Price'],
      dtype='object')

5. Muestra los valores únicos en la columna "Abbreviation".

In [11]:
df_data['Abbreviation'].unique()

array(['AF', 'AL', 'DZ', 'AD', 'AO', 'AG', 'AR', 'AM', 'AU', 'AT', 'AZ',
       'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BT', 'BO', 'BA',
       'BW', 'BR', 'BN', 'BG', 'BF', 'BI', 'CI', 'CV', 'KH', 'CM', 'CA',
       'CF', 'TD', 'CL', 'CN', 'CO', 'KM', nan, 'CR', 'HR', 'CU', 'CY',
       'CZ', 'CD', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER',
       'EE', 'ET', 'FJ', 'FI', 'FR', 'GA', 'GM', 'GE', 'DE', 'GH', 'GR',
       'GD', 'GT', 'GN', 'GW', 'GY', 'HT', 'HN', 'HU', 'IS', 'IN', 'ID',
       'IR', 'IQ', 'IL', 'IT', 'JM', 'JP', 'JO', 'KZ', 'KE', 'KI', 'KW',
       'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MG',
       'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MR', 'MU', 'MX', 'FM', 'MD',
       'MC', 'MN', 'ME', 'MA', 'MZ', 'MM', 'NR', 'NP', 'NL', 'NZ', 'NI',
       'NE', 'NG', 'KP', 'NO', 'OM', 'PK', 'PW', 'PA', 'PG', 'PY', 'PE',
       'PH', 'PL', 'PT', 'QA', 'RO', 'RU', 'RW', 'KN', 'LC', 'VC', 'WS',
       'SM', 'ST', 'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SK', 'SI', 'SB',
       'SO', 'ZA', 'KR', 'SS', 'ES', 'LK', 'SD', 'SR', 'SE', 'CH', 'SY',
       'TJ', 'TZ', 'TH', 'TL', 'TG', 'TO', 'TT', 'TN', 'TR', 'TM', 'TV',
       'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'UZ', 'VU', 'VE', 'VN', 'YE',
       'ZM', 'ZW'], dtype=object)

6. Cuenta cuántas veces aparece cada valor único en la columna "Abbreviation".

In [12]:
df_data['Abbreviation'].nunique()

188

7. Verifica si hay valores nulos en el conjunto de datos.

In [14]:
df_data.isnull().sum()

Country                   0
Density\n(P/Km2)          0
Abbreviation              7
Agricultural Land( %)     7
Land Area(Km2)            1
Armed Forces size        24
Birth Rate                6
Calling Code              1
Capital/Major City        3
Co2-Emissions             7
CPI                      17
CPI Change (%)           16
Currency-Code            15
Fertility Rate            7
Forested Area (%)         7
Gasoline Price           20
dtype: int64

8. Verifica si hay valores no nulos en el conjunto de datos.

In [15]:
df_data.notnull().sum()

Country                  195
Density\n(P/Km2)         195
Abbreviation             188
Agricultural Land( %)    188
Land Area(Km2)           194
Armed Forces size        171
Birth Rate               189
Calling Code             194
Capital/Major City       192
Co2-Emissions            188
CPI                      178
CPI Change (%)           179
Currency-Code            180
Fertility Rate           188
Forested Area (%)        188
Gasoline Price           175
dtype: int64

9. Muestra información general sobre el conjunto de datos.

In [16]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 195 entries, 0 to 194
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                195 non-null    object
 1   Density
(P/Km2)        195 non-null    object
 2   Abbreviation           188 non-null    object
 3   Agricultural Land( %)  188 non-null    object
 4   Land Area(Km2)         194 non-null    object
 5   Armed Forces size      171 non-null    object
 6   Birth Rate             189 non-null    float64
 7   Calling Code           194 non-null    float64
 8   Capital/Major City     192 non-null    object
 9   Co2-Emissions          188 non-null    object
 10  CPI                    178 non-null    object
 11  CPI Change (%)         179 non-null    object
 12  Currency-Code          180 non-null    object
 13  Fertility Rate         188 non-null    float64
 14  Forested Area (%)      188 non-null    object
 15  Gasoline Price         175 non-null    object
dtypes: float64(3), object(13)
memory usage: 25.9+ KB

10. Elimina una columna específica (por ejemplo, "Armed Forces size").

In [17]:
df_data.drop("Armed Forces size", axis = 1, inplace = True)
df_data.head(2)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price
0,Afghanistan,60,AF,58.10%,"652,230",32.49,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.47,2.10%,$0.70
1,Albania,105,AL,43.10%,"28,748",11.78,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.62,28.10%,$1.36

11. Selecciona las columnas numéricas del conjunto de datos y muestra sus estadísticas descriptivas básicas (para esto tendréis que usar el método '.describe(), su documentación la tenéis [aquí](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)).

In [18]:
df_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Birth Rate,189.0,20.214974,9.945774,5.90,11.300,17.950,28.7500,46.08
Calling Code,194.0,360.546392,323.236419,1.00,82.500,255.500,506.7500,1876.00
Fertility Rate,188.0,2.698138,1.282267,0.98,1.705,2.245,3.5975,6.91